name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install sfdx-cli
      - name: Authenticate DevHub Labs Developer Org
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername --setalias devhubldo
      - name: Create Scratch Org
        run: node_modules/sfdx-cli/bin/run force:org:create --targetdevhubusername devhubldo --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 1
      - name: Deploy source
        run: node_modules/sfdx-cli/bin/run force:source:push
      - name: "Unit test LWC"
        run: npm run test:unit:coverage
      - name: "Upload code coverage for LWC to Codecov.io"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: LWC
      - name: Delete Scratch Org
        run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt
